-- Migration 019: Phase 2C Detection Signal Types
-- QwickServices CIS — Adds 18 new signal_type enum values for 5 new detection consumers.
-- Note: 6 values (BOOKING_CANCEL_PATTERN, BOOKING_NO_SHOW_PATTERN, WALLET_VELOCITY_SPIKE,
--       WALLET_SPLIT_PATTERN, PROVIDER_RATING_DROP, PROVIDER_COMPLAINT_CLUSTER) already
--       exist from migration 016.

-- Booking anomaly signals
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'BOOKING_RAPID_CANCELLATION';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'BOOKING_FAKE_COMPLETION';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'BOOKING_SAME_PROVIDER_REPEAT';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'BOOKING_TIME_CLUSTERING';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'BOOKING_VALUE_ANOMALY';

-- Payment anomaly signals
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PAYMENT_CIRCULAR';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PAYMENT_RAPID_TOPUP';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PAYMENT_SPLIT_TRANSACTION';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PAYMENT_METHOD_SWITCHING';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PAYMENT_WITHDRAWAL_SPIKE';

-- Provider behavior signals
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PROVIDER_DUPLICATE_IDENTITY';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PROVIDER_RESPONSE_DEGRADATION';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PROVIDER_RATING_MANIPULATION';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'PROVIDER_CANCELLATION_SPIKE';

-- Temporal pattern signals
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'TEMPORAL_BURST_ACTIVITY';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'TEMPORAL_DORMANT_ACTIVATION';

-- Contact change signals
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'CONTACT_PHONE_CHANGED';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'CONTACT_EMAIL_CHANGED';
