-- Migration 034: Correlation Signal Types
-- Adds new signal types for cross-signal correlation detection.

ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'BOOKING_CANCEL_AFTER_CONTACT';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'REPEATED_UNPAID_BOOKING';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'DISCOUNT_OFFER_DETECTED';
ALTER TYPE signal_type ADD VALUE IF NOT EXISTS 'OFF_PLATFORM_TRANSACTION_CORRELATED';
